version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    # Disable version updates; security ones are not affected
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    # Disable version updates; security ones are not affected
    open-pull-requests-limit: 0

