name: Test
on:
  push: { }
  # Trigger this workflow on PRs created by Changesets by assigning it to
  # someone. We need this workaround because PRs created by GitHub Actions do
  # not trigger workflows per default.
  pull_request:
    branches: [ main ]
    types: [ assigned ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint source code
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build package
        run: npm run build
      - name: Check integrity of repository artifacts
        uses: Qualifyze/check-git-integrity-action@v1.0.0
